export interface Template {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  image: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    foreground: string;
  };
  features: string[];
  tags: string[];
}

export const templates: Template[] = [
  {
    id: "1",
    name: "Neo Brutalism",
    slug: "neo-brutalism",
    description: "Bold, raw design with thick borders, shadows, and vibrant colors",
    category: "Modern",
    image: "/templates/neo-brutalism.jpg",
    colors: {
      primary: "#000000",
      secondary: "#FFFF00",
      accent: "#FF00FF",
      background: "#FFFFFF",
      foreground: "#000000",
    },
    features: ["Thick borders", "Bold shadows", "High contrast", "Vibrant colors"],
    tags: ["bold", "modern", "vibrant"],
  },
  {
    id: "2",
    name: "Minimalist Clean",
    slug: "minimalist-clean",
    description: "Simple, elegant design with plenty of whitespace and subtle accents",
    category: "Minimal",
    image: "/templates/minimalist-clean.jpg",
    colors: {
      primary: "#1A1A1A",
      secondary: "#F5F5F5",
      accent: "#4A90E2",
      background: "#FFFFFF",
      foreground: "#1A1A1A",
    },
    features: ["Whitespace", "Clean typography", "Subtle animations", "Simple layout"],
    tags: ["minimal", "clean", "elegant"],
  },
  {
    id: "3",
    name: "Glassmorphism",
    slug: "glassmorphism",
    description: "Frosted glass effect with blur, transparency, and soft shadows",
    category: "Modern",
    image: "/templates/glassmorphism.jpg",
    colors: {
      primary: "#6366F1",
      secondary: "#8B5CF6",
      accent: "#EC4899",
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      foreground: "#FFFFFF",
    },
    features: ["Blur effects", "Transparency", "Soft shadows", "Gradient backgrounds"],
    tags: ["glass", "modern", "blur"],
  },
  {
    id: "4",
    name: "Skeuomorphism Modern",
    slug: "skeuomorphism-modern",
    description: "Realistic textures and shadows with modern twist",
    category: "Classic",
    image: "/templates/skeuomorphism.jpg",
    colors: {
      primary: "#2C3E50",
      secondary: "#34495E",
      accent: "#3498DB",
      background: "#ECF0F1",
      foreground: "#2C3E50",
    },
    features: ["Realistic shadows", "Textured surfaces", "3D effects", "Depth"],
    tags: ["realistic", "3d", "textured"],
  },
  {
    id: "5",
    name: "Claymorphism",
    slug: "claymorphism",
    description: "Soft, clay-like surfaces with smooth shadows and rounded corners",
    category: "Modern",
    image: "/templates/claymorphism.jpg",
    colors: {
      primary: "#FF6B6B",
      secondary: "#4ECDC4",
      accent: "#FFE66D",
      background: "#F7F7F7",
      foreground: "#2D3436",
    },
    features: ["Soft shadows", "Rounded corners", "Pastel colors", "3D depth"],
    tags: ["soft", "clay", "3d"],
  },
  {
    id: "6",
    name: "Cyberpunk Futuristic",
    slug: "cyberpunk-futuristic",
    description: "Neon colors, glitch effects, and futuristic elements",
    category: "Futuristic",
    image: "/templates/cyberpunk.jpg",
    colors: {
      primary: "#00FFFF",
      secondary: "#FF00FF",
      accent: "#FFFF00",
      background: "#0A0E27",
      foreground: "#00FFFF",
    },
    features: ["Neon colors", "Glitch effects", "Dark theme", "Futuristic fonts"],
    tags: ["neon", "dark", "futuristic"],
  },
  {
    id: "7",
    name: "Retro 80s",
    slug: "retro-80s",
    description: "Vibrant gradients, geometric shapes, and nostalgic vibes",
    category: "Retro",
    image: "/templates/retro-80s.jpg",
    colors: {
      primary: "#FF6B9D",
      secondary: "#C06C84",
      accent: "#F67280",
      background: "#355C7D",
      foreground: "#FFFFFF",
    },
    features: ["Gradients", "Geometric shapes", "Vibrant colors", "Retro fonts"],
    tags: ["retro", "80s", "vibrant"],
  },
  {
    id: "8",
    name: "Retro Pixel Art",
    slug: "retro-pixel-art",
    description: "8-bit inspired design with pixelated elements",
    category: "Retro",
    image: "/templates/pixel-art.jpg",
    colors: {
      primary: "#2D2D2D",
      secondary: "#46878F",
      accent: "#94E344",
      background: "#F4F4F4",
      foreground: "#2D2D2D",
    },
    features: ["Pixel fonts", "8-bit graphics", "Retro colors", "Grid layout"],
    tags: ["pixel", "8bit", "retro"],
  },
  {
    id: "9",
    name: "Dark Luxury",
    slug: "dark-luxury",
    description: "Premium dark theme with gold accents and elegant typography",
    category: "Premium",
    image: "/templates/dark-luxury.jpg",
    colors: {
      primary: "#D4AF37",
      secondary: "#1A1A1A",
      accent: "#C9A961",
      background: "#0D0D0D",
      foreground: "#FFFFFF",
    },
    features: ["Dark theme", "Gold accents", "Elegant fonts", "Premium feel"],
    tags: ["dark", "luxury", "premium"],
  },
  {
    id: "10",
    name: "Corporate Professional",
    slug: "corporate-professional",
    description: "Clean, professional design for business applications",
    category: "Business",
    image: "/templates/corporate.jpg",
    colors: {
      primary: "#003366",
      secondary: "#0066CC",
      accent: "#FF6600",
      background: "#FFFFFF",
      foreground: "#333333",
    },
    features: ["Professional layout", "Clean design", "Business colors", "Structured"],
    tags: ["corporate", "professional", "business"],
  },
  {
    id: "11",
    name: "Startup SaaS",
    slug: "startup-saas",
    description: "Modern SaaS design with gradients and clean interface",
    category: "SaaS",
    image: "/templates/saas.jpg",
    colors: {
      primary: "#6366F1",
      secondary: "#8B5CF6",
      accent: "#EC4899",
      background: "#FFFFFF",
      foreground: "#1F2937",
    },
    features: ["Gradient buttons", "Modern layout", "Clean UI", "Dashboard ready"],
    tags: ["saas", "modern", "startup"],
  },
  {
    id: "12",
    name: "AI Modern Interface",
    slug: "ai-modern-interface",
    description: "Futuristic AI-themed design with neural network aesthetics",
    category: "Tech",
    image: "/templates/ai-modern.jpg",
    colors: {
      primary: "#00D9FF",
      secondary: "#7C3AED",
      accent: "#F59E0B",
      background: "#0F172A",
      foreground: "#F1F5F9",
    },
    features: ["AI aesthetics", "Neural patterns", "Tech colors", "Modern UI"],
    tags: ["ai", "tech", "futuristic"],
  },
  {
    id: "13",
    name: "Gradient Vibrant",
    slug: "gradient-vibrant",
    description: "Colorful gradients with vibrant energy",
    category: "Colorful",
    image: "/templates/gradient-vibrant.jpg",
    colors: {
      primary: "#FF6B6B",
      secondary: "#4ECDC4",
      accent: "#FFE66D",
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      foreground: "#FFFFFF",
    },
    features: ["Vibrant gradients", "Colorful UI", "Energetic", "Modern"],
    tags: ["gradient", "vibrant", "colorful"],
  },
  {
    id: "14",
    name: "Monochrome Editorial",
    slug: "monochrome-editorial",
    description: "Black and white design with strong typography",
    category: "Editorial",
    image: "/templates/monochrome.jpg",
    colors: {
      primary: "#000000",
      secondary: "#FFFFFF",
      accent: "#666666",
      background: "#FFFFFF",
      foreground: "#000000",
    },
    features: ["B&W design", "Strong typography", "Editorial layout", "Minimal"],
    tags: ["monochrome", "editorial", "minimal"],
  },
  {
    id: "15",
    name: "Playful Colorful",
    slug: "playful-colorful",
    description: "Fun, colorful design with playful elements",
    category: "Playful",
    image: "/templates/playful.jpg",
    colors: {
      primary: "#FF6B9D",
      secondary: "#FFA07A",
      accent: "#98D8C8",
      background: "#FFF8E7",
      foreground: "#2D3436",
    },
    features: ["Playful colors", "Fun animations", "Rounded shapes", "Friendly"],
    tags: ["playful", "colorful", "fun"],
  },
  {
    id: "16",
    name: "Nature Organic",
    slug: "nature-organic",
    description: "Earth tones with organic shapes and natural feel",
    category: "Organic",
    image: "/templates/nature.jpg",
    colors: {
      primary: "#2D5016",
      secondary: "#7D8F69",
      accent: "#C9ADA7",
      background: "#F4F1DE",
      foreground: "#2D3436",
    },
    features: ["Earth tones", "Organic shapes", "Natural feel", "Eco-friendly"],
    tags: ["nature", "organic", "eco"],
  },
  {
    id: "17",
    name: "Japanese Zen",
    slug: "japanese-zen",
    description: "Minimalist Japanese-inspired design with zen aesthetics",
    category: "Zen",
    image: "/templates/japanese-zen.jpg",
    colors: {
      primary: "#8B4513",
      secondary: "#D4A574",
      accent: "#C41E3A",
      background: "#F5F5DC",
      foreground: "#2C2416",
    },
    features: ["Zen aesthetics", "Japanese typography", "Minimal", "Calm"],
    tags: ["japanese", "zen", "minimal"],
  },
  {
    id: "18",
    name: "Tech Dashboard",
    slug: "tech-dashboard",
    description: "Data-focused dashboard with charts and metrics",
    category: "Dashboard",
    image: "/templates/tech-dashboard.jpg",
    colors: {
      primary: "#1E3A8A",
      secondary: "#3B82F6",
      accent: "#10B981",
      background: "#F9FAFB",
      foreground: "#111827",
    },
    features: ["Dashboard layout", "Charts ready", "Data visualization", "Professional"],
    tags: ["dashboard", "tech", "data"],
  },
  {
    id: "19",
    name: "Bold Typography",
    slug: "bold-typography",
    description: "Typography-first design with bold, expressive fonts",
    category: "Typography",
    image: "/templates/bold-typography.jpg",
    colors: {
      primary: "#1A1A1A",
      secondary: "#FF4500",
      accent: "#FFD700",
      background: "#FFFFFF",
      foreground: "#1A1A1A",
    },
    features: ["Bold fonts", "Typography-focused", "Expressive", "Modern"],
    tags: ["typography", "bold", "expressive"],
  },
  {
    id: "20",
    name: "Gaming Theme",
    slug: "gaming-theme",
    description: "Gaming-inspired design with dynamic elements",
    category: "Gaming",
    image: "/templates/gaming.jpg",
    colors: {
      primary: "#9D00FF",
      secondary: "#00FF9D",
      accent: "#FF9D00",
      background: "#1A1A2E",
      foreground: "#EAEAEA",
    },
    features: ["Gaming aesthetics", "Dynamic UI", "Neon accents", "Dark theme"],
    tags: ["gaming", "dynamic", "neon"],
  },
];

export const categories = [
  "All",
  "Modern",
  "Minimal",
  "Classic",
  "Futuristic",
  "Retro",
  "Premium",
  "Business",
  "SaaS",
  "Tech",
  "Colorful",
  "Editorial",
  "Playful",
  "Organic",
  "Zen",
  "Dashboard",
  "Typography",
  "Gaming",
];
